"""Adicionar a coluna data_de_aniversario na tabela usuarios

Revision ID: 48bef3a0379a
Revises: fa2df0c51d57
Create Date: 2025-09-16 10:18:52.613516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48bef3a0379a'
down_revision: Union[str, Sequence[str], None] = 'fa2df0c51d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('data_de_aniversario', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'data_de_aniversario')
    # ### end Alembic commands ###
